### ISSUE TITLE
Supporting distros

### ISSUE THREAD

**Issue by friday** [friday/Legacy-Ulauncher-Fork#2]
Currently supported distros:
* [Arch](https://aur.archlinux.org/packages/ulauncher-revived-git/) (installs straight from git `dev` branch)

================================================

My first priority is to keep this project working for people building from source. I don't want to start taking over package names, or creating new ones to point here, and reading up on how to support different package managers. Hopefully gornostal will return and it won't be necessary.

Since I did just mention this fork in a couple of github PR's people will be coming here expecting all of that though. Please be patient, build from source, or offer to help out.

**Comment by danielhass** [comment]
@friday - thanks for picking up the work on this "soft-fork".

As Arch is one of the GTK 4 default distros that ran into severe problems with ulauncher I could jump in an provide a forked AUR package from the official one and maintain it in the meantime: https://aur.archlinux.org/packages/ulauncher
This maybe makes it easier for folks to switch over to your fork and hopefully back later.

Will you provided "releases" or some kind of "fork-versions" on this repo for somewhat stable versions? Or is the `dev` branch considered to be the latest stable state of your fork. Any plans on this yet?

**Comment by friday** [comment]
Thank you @danielhass 
I want to make it easy for myself and others initially, and won't be making releases until I can fix some more of the big issues and low hanging fruits. If you looked into the complexity of Ulaunchers build scripts and dependencies you would understand why.

I use Arch too. You can actually just download the https://aur.archlinux.org/packages/ulauncher-git one and point to this repo instead and it should work (does for me at least). It's actually how I install the app now (pointing to my local dev directory), because [I really don't like the dev environment/scripts](https://github.com/friday/Ulauncher-Revived/discussions/10). I plan to start by forking that and uploading, but I never submitted a package before. I also prefer to run via systemd. I'm not sure this should be the standard for arch or not, or for all/most distros. I mostly prefer it because ulauncher crashes on libx11 segfaults (#4).

**Comment by friday** [comment]
@danielhass You can now install [ulauncher-revived-git](https://aur.archlinux.org/packages/ulauncher-revived-git/)

**Comment by danielhass** [comment]
@friday thank you for the package! Sadly it does not seem to work on my machine.. the same error popped up when I initially tried to install the revived version via the method proposed above (switching the *-git version to your repo).

```
yarn run v1.22.10
$ node build/build.js
Error: Cannot find module 'bluebird'
Require stack:
- /usr/lib/node_modules/npm/node_modules/make-fetch-happen/node_modules/cacache/lib/entry-index.js
- /usr/lib/node_modules/npm/node_modules/make-fetch-happen/node_modules/cacache/ls.js
- /usr/lib/node_modules/npm/node_modules/make-fetch-happen/node_modules/cacache/locales/en.js
- /usr/lib/node_modules/npm/node_modules/make-fetch-happen/node_modules/cacache/index.js
- /usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/entry.js
- /usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/index.js
- /usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/fetch.js
- /usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/index.js
- /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/index.js
- /usr/lib/node_modules/npm/node_modules/pacote/lib/remote.js
- /usr/lib/node_modules/npm/node_modules/pacote/lib/git.js
- /usr/lib/node_modules/npm/node_modules/pacote/lib/fetcher.js
- /usr/lib/node_modules/npm/node_modules/pacote/lib/index.js
- /usr/lib/node_modules/npm/lib/utils/update-notifier.js
- /usr/lib/node_modules/npm/lib/cli.js
- /usr/lib/node_modules/npm/bin/npm-cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
    at Function.Module._load (node:internal/modules/cjs/loader:772:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/node_modules/cacache/lib/entry-index.js:3:12)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
/usr/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:182
      throw new Error('call config.load() before reading values')
      ^

Error: call config.load() before reading values
    at Config.get (/usr/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:182:13)
    at process.errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:181:32)
    at process.emit (node:events:394:28)
    at process._fatalException (node:internal/process/execution:170:25)
node:child_process:903
    throw err;
    ^

Error: Command failed: npm --version
Error: Cannot find module 'bluebird'
Require stack:
- /usr/lib/node_modules/npm/node_modules/make-fetch-happen/node_modules/cacache/lib/entry-index.js
- /usr/lib/node_modules/npm/node_modules/make-fetch-happen/node_modules/cacache/ls.js
- /usr/lib/node_modules/npm/node_modules/make-fetch-happen/node_modules/cacache/locales/en.js
- /usr/lib/node_modules/npm/node_modules/make-fetch-happen/node_modules/cacache/index.js
- /usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/entry.js
- /usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/index.js
- /usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/fetch.js
- /usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/index.js
- /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/index.js
- /usr/lib/node_modules/npm/node_modules/pacote/lib/remote.js
- /usr/lib/node_modules/npm/node_modules/pacote/lib/git.js
- /usr/lib/node_modules/npm/node_modules/pacote/lib/fetcher.js
- /usr/lib/node_modules/npm/node_modules/pacote/lib/index.js
- /usr/lib/node_modules/npm/lib/utils/update-notifier.js
- /usr/lib/node_modules/npm/lib/cli.js
- /usr/lib/node_modules/npm/bin/npm-cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
    at Function.Module._load (node:internal/modules/cjs/loader:772:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/node_modules/cacache/lib/entry-index.js:3:12)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
/usr/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:182
      throw new Error('call config.load() before reading values')
      ^

Error: call config.load() before reading values
    at Config.get (/usr/lib/node_modules/npm/node_modules/@npmcli/config/lib/index.js:182:13)
    at process.errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:181:32)
    at process.emit (node:events:394:28)
    at process._fatalException (node:internal/process/execution:170:25)

    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at exec (/home/<user>/.cache/yay/ulauncher-revived-git/src/ulauncher/data/preferences/build/check-versions.js:6:35)
    at Object.<anonymous> (/home/<user>/.cache/yay/ulauncher-revived-git/src/ulauncher/data/preferences/build/check-versions.js:20:21)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18) {
  status: 7,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(2410) [Uint8Array] [
       69, 114, 114, 111, 114,  58,  32,  67,  97, 110, 110, 111,
      116,  32, 102, 105, 110, 100,  32, 109, 111, 100, 117, 108,
      101,  32,  39,  98, 108, 117, 101,  98, 105, 114, 100,  39,
       10,  82, 101, 113, 117, 105, 114, 101,  32, 115, 116,  97,
       99, 107,  58,  10,  45,  32,  47, 117, 115, 114,  47, 108,
      105,  98,  47, 110, 111, 100, 101,  95, 109, 111, 100, 117,
      108, 101, 115,  47, 110, 112, 109,  47, 110, 111, 100, 101,
       95, 109, 111, 100, 117, 108, 101, 115,  47, 109,  97, 107,
      101,  45, 102, 101,
      ... 2310 more items
    ]
  ],
  pid: 15480,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(2410) [Uint8Array] [
     69, 114, 114, 111, 114,  58,  32,  67,  97, 110, 110, 111,
    116,  32, 102, 105, 110, 100,  32, 109, 111, 100, 117, 108,
    101,  32,  39,  98, 108, 117, 101,  98, 105, 114, 100,  39,
     10,  82, 101, 113, 117, 105, 114, 101,  32, 115, 116,  97,
     99, 107,  58,  10,  45,  32,  47, 117, 115, 114,  47, 108,
    105,  98,  47, 110, 111, 100, 101,  95, 109, 111, 100, 117,
    108, 101, 115,  47, 110, 112, 109,  47, 110, 111, 100, 101,
     95, 109, 111, 100, 117, 108, 101, 115,  47, 109,  97, 107,
    101,  45, 102, 101,
    ... 2310 more items
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Don't know if this is a issue specific to my machine?

**Comment by friday** [comment]
> Don't know if this is a issue specific to my machine?

It shouldn't be, but it seems like it. I'm not getting the issue, and the error stack traces involves NPM internal dependencies, and it said it crashed when running `npm --version`?

Did you try installing https://github.com/Jguer/yay and the running `yay -S ulauncher-revived-git`? It worked for me just now with a clean build. Pamac (aka "Add/Remove Software") works too if you enable AUR.

I wish I could help more, but I already had too much going on before taking this project on. If it doesn't work, you can keep using Ulauncher with the extensions that work until I make a release with the node part pre-built.

**Comment by friday** [comment]
@danielhass: If you're ready to try this again, please let me know the output of
`pacman -Q npm nodejs`.

Install and upgrade both of these if needed, and check the output of `node --version` and `npm --version`
If they are either broken or show a different version than the `pacman -Q` command, please also run `which npm`and `which npm`.

What I want to make sure is that your npm version and your node version are functional and compatible, because it seems to not be the case.

**Comment by danielhass** [comment]
@friday sorry for my late reply. It seems that you are totally right with your assumption.

`npm` seems to be broken on my system. Sorry that I didn't notice that early!

```
npm --version
Error: Cannot find module 'bluebird'
Require stack:
- /usr/lib/node_modules/npm/node_modules/make-fetch-happen/node_modules/cacache/lib/entry-index.js
- /usr/lib/node_modules/npm/node_modules/make-fetch-happen/node_modules/cacache/ls.js
- /usr/lib/node_modules/npm/node_modules/make-fetch-happen/node_modules/cacache/locales/en.js
- /usr/lib/node_modules/npm/node_modules/make-fetch-happen/node_modules/cacache/index.js
- /usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/entry.js
- /usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/index.js
- /usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/fetch.js
- /usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/index.js
- /usr/lib/node_modules/npm/node_modules/npm-registry-fetch/index.js
- /usr/lib/node_modules/npm/node_modules/pacote/lib/remote.js
- /usr/lib/node_modules/npm/node_modules/pacote/lib/git.js
- /usr/lib/node_modules/npm/node_modules/pacote/lib/fetcher.js
- /usr/lib/node_modules/npm/node_modules/pacote/lib/index.js
- /usr/lib/node_modules/npm/lib/utils/update-notifier.js
- /usr/lib/node_modules/npm/lib/cli.js
- /usr/lib/node_modules/npm/bin/npm-cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
    at Function.Module._load (node:internal/modules/cjs/loader:772:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/node_modules/cacache/lib/entry-index.js:3:12)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
```

I will check whats wrong there in a free minute.

```
npm 7.20.1-1
nodejs 16.5.0-1
```
